0:
  title: "ThingsBoard data modeling and visualization (sessions 1)"
  additionalText: "2 hours"
  additionalFaIcon : "far fa-clock fa-lg"
  allTextContentIcon: "fas fa-check"
  textContentCollection:
    0:
      textContent: "Overview of TB hierarchy and main features based on real examples."
    1:
      textContent: "Devices, Assets, Entity Views, Customers, Users, and Dashboards based on real-life examples."
    2:
      textContent: "Explain ThingsBoard entity attributes and telemetry APIs. Overview of best practices with the naming of data keys and usage of the APIs."
    3:
      textContent: "Device and Asset Groups (PE feature). Covers configuration of the groups and usage scenarios."
    4:
      textContent: "Entity relations. Covers entity relation types, usage scenarios, and limitations."
    5:
      textContent: "The dashboard features overview: Covers entity Aliases, Time Window selection, General Settings, Dashboard states, and transition between states."
    6:
      textContent: "Q&A (questions and answers)."
1:
  title: "ThingsBoard data modeling and visualization (sessions 2)"
  additionalText: "2 hours"
  additionalFaIcon : "far fa-clock fa-lg"
  allTextContentIcon: "fas fa-check"
  textContentCollection:
    0:
      textContent: "Creating a dashboard with multiple states to display Asset hierarchy with the ability to drill down to particular asset/device details."
    1:
      textContent: "Exploring advanced configuration of Chart, Markdown/HTML Card, and Map widgets."
    2:
      textContent: "Custom Tooltip functions and custom Dashboard Actions."
    3:
      textContent: "Q&A (questions and answers)."
2:
  title: "ThingsBoard custom widget development (sessions 1)"
  additionalText: "2 hours"
  additionalFaIcon : "far fa-clock fa-lg"
  allTextContentIcon: "fas fa-check"
  textContentCollection:
    0:
      textContent: "Creating new bundles/widgets. Modifying system-bundles. Import/Export bundles and widgets. Built editor overview."
    1:
      textContent: "Building “Last values”-type widget."
    2:
      textContent: "Building “Timeseries”-type widget(simple time-series-table or line-chart)."
    3:
      textContent: "Custom actions and custom actions templates with HTML."
    4:
      textContent: "Q&A (questions and answers)."
3:
  title: "ThingsBoard custom widget development (sessions 2)"
  additionalText: "2 hours"
  additionalFaIcon : "far fa-clock fa-lg"
  allTextContentIcon: "fas fa-check"
  textContentCollection:
    0:
      textContent: "Building a “Control”-type widget."
    1:
      textContent: "Building a “Static”-type widget."
    2:
      textContent: "Building Markdown/HTML Card based widget."
    3:
      textContent: "Q&A (questions and answers)."
