0:
  title: "Device connectivity, data processing, and visualization"
  additionalText: "2 hours"
  additionalFaIcon : "far fa-clock fa-lg"
  allTextContentIcon: "fas fa-check"
  textContentCollection:
    0:
      textContent: "Connecting devices and retrieving data using transport protocols (HTTP, MQTT, CoAP, LWM2M), integrations with external systems, and ThingsBoard Gateway."
    1:
      textContent: "Configuring an emulator to send data via MQTT and displaying it in real-time."
    2:
      textContent: "Processing data through the default rule chain and setting up a custom rule chain."
    3:
      textContent: "Configuring dashboard widgets and customizing layouts to display incoming data effectively."
    4:
      textContent: "Q&A (questions and answers)."
1:
  title: "Basics and interface operation"
  additionalText: "2 hours"
  additionalFaIcon : "far fa-clock fa-lg"
  allTextContentIcon: "fas fa-check"
  textContentCollection:
    0:
      textContent: "Introduction to SCADA user interface capabilities."
    1:
      textContent: "Creating a basic dashboard: using existing symbols and their configurations."
    2:
      textContent: "Overview of layout settings: grid, toolbar, and scaling options."
    3:
      textContent: "Customizing the user interface for various operational scenarios."
    4:
      textContent: "Q&A (questions and answers)."
2:
  title: "Advanced use, tags, behaviors, and properties"
  additionalText: "2 hours"
  additionalFaIcon : "far fa-clock fa-lg"
  allTextContentIcon: "fas fa-check"
  textContentCollection:
    0:
      textContent: "Working with the library of existing symbols: searching, configuring, and adding."
    1:
      textContent: "Creating a new SCADA symbol"
    2:
      textContent: "Working with tags: editor or XML"
    3:
      textContent: 'Defining behavior parameters: “Value,” “Action,” and “Widget action”.'
    4:
      textContent: "Configuring properties: static and dynamic parameters."
    5:
      textContent: "Working with tag functions: principles of data binding, animations, and event reactions."
    6:
      textContent: "Preview, create widget, and bundle. Add it to the dashboard."
    7:
      textContent: "Q&A (questions and answers)."
